### PR TITLE
Remove Evolvis releases repo

### PR DESCRIPTION
**Pull request by tkrille**
There are no releases on the Evolvis releases repo, that we wouldn't get
from the central too.

### CODE REVIEW

**Comment by dacrome** [comment]
Please rebase

**Comment by tkrille** [comment]
According to my information, this is already merged.

**Comment by dacrome** [comment]
Strange. It's merged, but the Pull Request was not in the closed list.

**Comment by tkrille** [comment]
It seems, that this commit was contained in another merged PR.

**Pull request closed without merging**
